### ISSUE TITLE
Add custom repositories to lists.yaml

### ISSUE THREAD

**Issue by thetredev** [thetredev/xdeb-install-repositories#1]
maybe:
```yaml
providers:
  - name: google.com
    custom: true # infers that 'components' are yaml definitions
    architecture: amd64
    url: https://raw.githubusercontent.com/thetredev/xdeb-install-repositories/main/repositories/x86_64/google.com
    components:
      - google-chrome
    dists:
      - current
```
