### ISSUE TITLE
Add post-install hooks to custom packages

### ISSUE THREAD

**Issue by thetredev** [thetredev/xdeb-install-repositories#3]
See https://github.com/thetredev/xdeb-install/issues/9 for the reasoning behind this issue.

Implementation could look something like this:
```yaml
xdeb:
  - name: vscode
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    # shell commands to execute
    post-install:
      - name: Link 'code' executable # used in xdeb-install to print the hook
        root: true
        commands:
          - ln -sf /usr/share/code/bin/code /usr/local/bin/code
```
